name: Deploy Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'snapshot/*'

jobs:
  call-template:
    uses: ./.github/workflows/template.yml
    with:
      branch: ${{ github.ref }}
      branch_type: ${{ github.ref == 'refs/heads/feature/' && 'feature' || github.ref == 'refs/heads/snapshot/' && 'snapshot' || 'unknown' }}
