name: Deploy Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'teams/*'
      - 'snapshot/*'
      - 'develop/*'  # Include develop branches

jobs:
  call-template:
    uses: ./.github/workflows/template.yml
    with:
      branch: ${{ github.ref }}
      branch_type: ${{ github.ref }}
      allowed_branch_types: 'feature,teams,snapshot,develop'  # Pass the branch types as a comma-separated string
