name: Template Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      branch_type:
        required: true
        type: string
      allowed_branch_types:
        required: true
        type: string

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Building from branch: ${{ inputs.branch }}"
          echo "Branch type being checked: ${{ inputs.branch_type }}"
          echo "Allowed branch types: ${{ inputs.allowed_branch_types }}"

          # Split the allowed_branch_types string into an array
          IFS=',' read -r -a branch_types_array <<< "${{ inputs.allowed_branch_types }}"

          # Initialize variables
          current_branch="${{ inputs.branch_type }}"
          allowed=false
          branch_type_name=""

          # Special case for main branch
          if [[ "$current_branch" == "refs/heads/main" ]]; then
            allowed=true
            branch_type_name="release"  # Set type name for logging
          else
            # Check if the current branch matches any allowed branch types
            for type in "${branch_types_array[@]}"; do
              IFS=':' read -r type_name patterns <<< "$type"
              IFS=',' read -r -a pattern_array <<< "$patterns"
              for pattern in "${pattern_array[@]}"; do
                echo "Checking pattern: $pattern against branch: $current_branch"
                if [[ "$current_branch" == "refs/heads/$pattern"* ]]; then
                  allowed=true
                  branch_type_name="$type_name"
                  break 2
                fi
              done
            done
          fi

          if [[ "$allowed" == true ]]; then
            echo "Current branch type is allowed: $current_branch ($branch_type_name)"
            echo "Build completed."
          else
            echo "Current branch type is not allowed: $current_branch"
            exit 1
          fi

  snapshot_job:
    runs-on: ubuntu-latest
    needs: 
      - build_job
    if: startsWith(inputs.branch_type, 'refs/heads/snapshot/') || startsWith(inputs.branch_type, 'refs/heads/develop/')
    steps:
      - name: Create Snapshot
        run: |
          echo "Creating snapshot from branch: ${{ inputs.branch }}"
          echo "Snapshot created."

  rc_job:
    runs-on: ubuntu-latest
    needs: 
      - build_job
      - snapshot_job
    if: startsWith(inputs.branch_type, 'refs/heads/develop/')
    steps:
      - name: Release Candidate Job
        run: |
          echo "Running RC job for branch: ${{ inputs.branch }}"
          echo "Release candidate job completed."

  release_job:
    runs-on: ubuntu-latest
    needs: 
      - build_job
      - snapshot_job
      - rc_job
    if: startsWith(inputs.branch_type, 'refs/heads/main')
    steps:
      - name: Release Job
        run: |
          echo "Running release job for branch: ${{ inputs.branch }}"
          echo "Release job completed."
