name: Template Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      branch_type:
        required: true
        type: string

jobs:
  build_job:
    runs-on: ubuntu-latest
    if: startsWith(inputs.branch_type, 'refs/heads/feature/') || startsWith(inputs.branch_type, 'refs/heads/snapshot/')
    steps:
      - name: Build
        run: |
          echo "Building from branch: ${{ inputs.branch }}"
          if [[ "${{ inputs.branch_type }}" == refs/heads/feature/* ]]; then
            echo "Build for feature branch"
          else
            echo "Build for snapshot branch"
          fi
          echo "Build completed."

  snapshot_job:
    runs-on: ubuntu-latest
    if: startsWith(inputs.branch_type, 'refs/heads/snapshot/')
    steps:
      - name: Create Snapshot
        run: |
          echo "Creating snapshot from branch: ${{ inputs.branch }}"
          # Add your snapshot logic here
          echo "Snapshot created."
