name: Template Workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  feature_job:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Feature Branch
        run: ${{ inputs.branch }}"

  develop_job:
    if: startsWith(github.ref, 'refs/heads/develop/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Develop Branch
        run: ${{ inputs.branch }}"

  rc_job:
    if: startsWith(github.ref, 'refs/heads/rc/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Release Candidate Branch
        run: ${{ inputs.branch }}"
